lesson_10_task_3
Sguruu/kurs_kotlin_basic pull request #12
Opened 2024-05-20 07:00 UTC by Sguruu

2024-05-20 07:17 UTC, ievetrovdev requested changes

2024-05-20 07:17 UTC, ievetrovdev commented on lesson_10/Task_3.kt
> +    val specialSymbols = "!\"#\$%&'()*+,-./ "
Попробуй представить последовательность символов в виде диапазона. Подробнее тут https://ru.wikipedia.org/wiki/ASCII

2024-06-10 06:24 UTC, Sguruu commented on lesson_10/Task_3.kt
> +    val specialSymbols = "!\"#\$%&'()*+,-./ "
Спасибо ! А как мне понять что именно нужно было указывать '!'..' ' ? Почитал статью, но все равно не понял откуда брать эту информацию ? (сделал с помощью подсказки ИИ, но хотелось бы самому понять откуда брать понимание нужных диапазонов ?)

2024-06-10 15:11 UTC, ievetrovdev commented on lesson_10/Task_3.kt
> +    val specialSymbols = "!\"#\$%&'()*+,-./ "
Перебор идёт по порядковому номеру, а номера можно найти в таблице. К примеру тут https://snipp.ru/handbk/table-ascii

2024-06-10 15:13 UTC, ievetrovdev requested changes
Ответил

2024-06-10 15:13 UTC, ievetrovdev commented on lesson_10/Task_3.kt
> +    for (i in 1..passwordLength.toInt() step 2) {
А если будет не чётное количество символов, то шаг в 2 не подойдёт, попробую решить с шагом в 1

2024-06-10 15:20 UTC, Sguruu commented on lesson_10/Task_3.kt
> +    val specialSymbols = "!\"#\$%&'()*+,-./ "
Спасибо ! Судя по таблице, спец символы идут в следующем порядке от 33 до 47, значит я должен был указать val specialSymbols = '!'..'/' верно я понимаю ?

2024-06-10 15:23 UTC, Sguruu commented on lesson_10/Task_3.kt
> +    for (i in 1..passwordLength.toInt() step 2) {
А разве нечетное количество символов сможет удовлетворить условию задачи ? 
 - Пароль должен состоять из последовательно чередующихся цифр и
специальных символов. Например, 4#4%2!

Просто по условию всегда будет пара, где первое значение это цифра, а второе значение это специальный символ

2024-06-10 15:23 UTC, Sguruu commented on lesson_10/Task_3.kt
> +    for (i in 1..passwordLength.toInt() step 2) {
А если всегда будет пара, следовательно то могу делать шаг в 2

2024-06-10 15:24 UTC, Sguruu commented on lesson_10/Task_3.kt
> +    for (i in 1..passwordLength.toInt() step 2) {
Если изменишь условие задачи (надеюсь не против, если на ты, если против то напиши пожалуйста), попробую сделать с шагом в 1.

2024-06-11 15:53 UTC, ievetrovdev commented on lesson_10/Task_3.kt
> +    val specialSymbols = "!\"#\$%&'()*+,-./ "
C Пробела до / : `' '..'/'`

2024-06-11 15:56 UTC, ievetrovdev requested changes
Ответил

2024-06-11 15:56 UTC, ievetrovdev commented on lesson_10/Task_3.kt
> +    for (i in 1..passwordLength.toInt() step 2) {
Чередование это не означает что обязательно пара. Чередование - значит не должно быть символа, который бы нарушил правило чередования.

2024-06-11 19:16 UTC, Sguruu commented on lesson_10/Task_3.kt
> +    for (i in 1..passwordLength.toInt() step 2) {
ааа понял

2024-06-11 19:16 UTC, Sguruu commented on lesson_10/Task_3.kt
> +    val specialSymbols = "!\"#\$%&'()*+,-./ "
ага понял спасибо !

2024-06-11 21:29 UTC, ievetrovdev approved these changes
Все верно, отличное решение!

2024-06-12 14:38 UTC, merged