Lesson 10 task 5
Sguruu/kurs_kotlin_basic pull request #13
Opened 2024-06-10 07:02 UTC by Sguruu

2024-06-10 19:52 UTC, ievetrovdev requested changes

2024-06-10 19:52 UTC, ievetrovdev commented on lesson_10/Task_5.kt
> +private fun getUserBasket(accessToken: String): String = "Ваша корзина : Яйцо, Сосиска, Молоко."
Метод должен возвращать список товаров, а не строку. (лист строк например)

2024-06-10 19:52 UTC, ievetrovdev commented on lesson_10/Task_5.kt
> +private fun generateAccessToken(): String {
Метод можно упростить, используя метод joinToString для объединения символов в строку.

2024-06-10 19:52 UTC, ievetrovdev commented on lesson_10/Task_5.kt
> +private fun Int.forEach(forEach: () -> Unit) {
Метод не нужен, можно использовать стандартный метод repeat.

2024-06-11 06:07 UTC, Sguruu commented on lesson_10/Task_5.kt
> +private fun getUserBasket(accessToken: String): String = "Ваша корзина : Яйцо, Сосиска, Молоко."
+++

2024-06-11 06:11 UTC, Sguruu commented on lesson_10/Task_5.kt
> +private fun generateAccessToken(): String {
спасибо ! поправил

2024-06-11 06:17 UTC, Sguruu commented on lesson_10/Task_5.kt
> +private fun Int.forEach(forEach: () -> Unit) {
поправил, спасибо

2024-06-11 16:00 UTC, ievetrovdev approved these changes
Все  верно, молодец!

2024-06-11 19:14 UTC, merged