Lesson 11 Task 3
Sguruu/kurs_kotlin_basic pull request #21
Opened 2024-06-11 20:30 UTC by Sguruu

2024-06-12 19:16 UTC, ievetrovdev requested changes

2024-06-12 19:16 UTC, ievetrovdev commented on lesson_11/Task_3.kt
> +internal data class User(
Просто class, на данном этапе обучения

2024-06-12 19:16 UTC, ievetrovdev commented on lesson_11/Task_3.kt
> +    println(room.users)
можно вывести информацию о комнате в более читаемом виде, например, используя метод joinToString для списка пользователей

2024-06-12 19:16 UTC, ievetrovdev commented on lesson_11/Task_3.kt
> +            user.nickName == nickName
Ник такая не постоянная вещь, давай лучше сделаем id для пользователей

2024-06-13 06:50 UTC, Sguruu commented on lesson_11/Task_3.kt
> +internal data class User(
сделал private чтобы было проще работать в проекте (могу переиспользовать имена классов спокойно)

2024-06-13 06:50 UTC, Sguruu commented on lesson_11/Task_3.kt
> +    println(room.users)
+++

2024-06-13 06:51 UTC, Sguruu commented on lesson_11/Task_3.kt
> +            user.nickName == nickName
+++

2024-06-13 20:15 UTC, ievetrovdev requested changes

2024-06-13 20:15 UTC, ievetrovdev commented on lesson_11/Task_3.kt
> +    fun addUser(user: User) {
Нет проверки уникальности Id. Это можно решить, проставляя его прям в этом методе, а не принимая как параметр. Как результат можно вернуть экземпляр пользователя после добавления (с новым id и тд)

2024-06-15 09:28 UTC, ievetrovdev approved these changes
Все верно! Отличное решение!

2024-06-18 18:23 UTC, merged