Lesson 11 Task 5
Sguruu/kurs_kotlin_basic pull request #22
Opened 2024-06-11 21:02 UTC by Sguruu

2024-06-11 21:48 UTC, ievetrovdev requested changes

2024-06-11 21:48 UTC, ievetrovdev commented on lesson_11/Task_5.kt
> +internal class MemberForum(val userId: Int, val userName: String)
Просто class

2024-06-11 21:48 UTC, ievetrovdev commented on lesson_11/Task_5.kt
> +internal class MessageForum(val authorId: Int, val message: String)
Просто class

2024-06-11 21:48 UTC, ievetrovdev commented on lesson_11/Task_5.kt
> +    private fun generateId(): Int = Random.nextInt()
Идентификаторы должны быть всегда уникальные, лучше использовать последовательность: 1, 2, 3 ... Случайные числа могут повториться

2024-06-11 21:48 UTC, ievetrovdev commented on lesson_11/Task_5.kt
> +    private fun generateId(): Int = Random.nextInt()
Хотя и с рандомом можно организовать последовательность

2024-06-11 21:48 UTC, ievetrovdev commented on lesson_11/Task_5.kt
> +internal class MemberForum(val userId: Int, val userName: String)
Можно переопределить метод toString, чтобы он возвращал имя пользователя. Тогда в методе printThread можно будет просто печатать объект MemberForum.

2024-06-11 21:48 UTC, ievetrovdev commented on lesson_11/Task_5.kt
> +        if (listUsers.any { it.userId == userId }) {
Выведи ошибку, если пользователь не найден

2024-06-12 15:02 UTC, Sguruu commented on lesson_11/Task_5.kt
> +internal class MemberForum(val userId: Int, val userName: String)
не понял про переопределение метода toString, для какого класса нужно переопределять ?

Просто по условия мы должны вывести в таком формате автор : сообщение
Автор берется из класса MemberForum, а сообщение берется из класса MessageForum.

2024-06-12 15:02 UTC, Sguruu commented on lesson_11/Task_5.kt
> +internal class MessageForum(val authorId: Int, val message: String)
поправил

2024-06-12 15:02 UTC, Sguruu commented on lesson_11/Task_5.kt
> +    private fun generateId(): Int = Random.nextInt()
поправил

2024-06-12 15:04 UTC, Sguruu commented on lesson_11/Task_5.kt
> +        if (listUsers.any { it.userId == userId }) {
+++

2024-06-12 19:21 UTC, ievetrovdev approved these changes
Все верно!

2024-06-12 19:22 UTC, ievetrovdev commented on lesson_11/Task_5.kt
> +internal class MemberForum(val userId: Int, val userName: String)
В целом да, лучше не усложнять и оставить так.

2024-06-13 06:52 UTC, merged