Lesson 12 Task 3
Sguruu/kurs_kotlin_basic pull request #24
Opened 2024-06-12 16:25 UTC by Sguruu

2024-06-13 07:21 UTC, ievetrovdev requested changes

2024-06-13 07:21 UTC, ievetrovdev commented on lesson_12/Task_3.kt
> +    constructor(
Давай сократим немного код и параметры конструктора перенесем в класс
```
class WeatherDataTask3(
    daytimeTemperatureKelvin: Int,
    nightTemperatureKelvin: Int,
) 
```

2024-06-13 07:21 UTC, ievetrovdev commented on lesson_12/Task_3.kt
> +    var daytimeTemperature: Int = 12
Зачем здесь значения по умолчанию если мы их в конструкторе сразу перезаписываем?
Давай сделаем таким образом: `val daytimeTemperature: Int = daytimeTemperatureKelvin - 273`

2024-06-13 07:21 UTC, ievetrovdev commented on lesson_12/Task_3.kt
> +        this.daytimeTemperature = daytimeTemperatureKelvin - 273
273 стоит вынести в константу

2024-06-18 18:33 UTC, Sguruu commented on lesson_12/Task_3.kt
> +    constructor(
поправил

2024-06-18 18:33 UTC, Sguruu commented on lesson_12/Task_3.kt
> +    var daytimeTemperature: Int = 12
поправил

2024-06-18 18:33 UTC, Sguruu commented on lesson_12/Task_3.kt
> +        this.daytimeTemperature = daytimeTemperatureKelvin - 273
поправил

2024-06-19 05:32 UTC, ievetrovdev approved these changes

2024-06-19 16:33 UTC, merged