Lesson 12 Task 5
Sguruu/kurs_kotlin_basic pull request #25
Opened 2024-06-12 17:43 UTC by Sguruu

2024-06-19 06:03 UTC, ievetrovdev requested changes

2024-06-19 06:03 UTC, ievetrovdev commented on lesson_12/Task_5.kt
> +    var isPrecipitation: Boolean = true
Почему бы нам не сократить и не упростить код, чтобы все объекты сразу создавались с входными данными? Сейчас получается что у всех объектов изначально есть осадки
`class WeatherDataTask5(kelvinDayTemperature: Int, kelvinNightTemperature: Int, isPrecipitation: Boolean) `

Тогда не придется делать отдельный громоздкий конструктор

2024-06-19 16:45 UTC, Sguruu commented on lesson_12/Task_5.kt
> +    var isPrecipitation: Boolean = true
хотел сделать класс более гибким, чтобы можно было при создании вводить как кельвины так и Цельсии

2024-06-19 16:48 UTC, Sguruu commented on lesson_12/Task_5.kt
> +    var isPrecipitation: Boolean = true
поправил

2024-06-20 07:08 UTC, ievetrovdev commented on lesson_12/Task_5.kt
> +    var isPrecipitation: Boolean = true
> хотел сделать класс более гибким, чтобы можно было при создании вводить как кельвины так и Цельсии

Это выглядит слишком не очевидно и лучше было бы сделать отдельный класс, который бы принимал температуру в Цельсиях

2024-06-20 07:08 UTC, ievetrovdev approved these changes

2024-06-27 16:16 UTC, merged