Lesson 14 Task 1
Sguruu/kurs_kotlin_basic pull request #28
Opened 2024-06-12 19:55 UTC by Sguruu

2024-06-18 19:24 UTC, ievetrovdev requested changes

2024-06-18 19:24 UTC, ievetrovdev commented on lesson_14/Task_1.kt
> +     */
Комментарии не нужны

2024-06-18 19:24 UTC, ievetrovdev commented on lesson_14/Task_1.kt
> +     */
Комментарии не нужны

2024-06-19 16:50 UTC, Sguruu commented on lesson_14/Task_1.kt
> +     */
удалил

2024-06-19 16:50 UTC, Sguruu commented on lesson_14/Task_1.kt
> +     */
удалил

2024-06-19 19:35 UTC, ievetrovdev approved these changes
Все верно, молодец!

2024-06-27 16:20 UTC, merged