Lesson 7 task 3
Sguruu/kurs_kotlin_basic pull request #3
Opened 2024-03-13 06:40 UTC by Sguruu

2024-03-13 15:21 UTC, ievetrovdev requested changes

2024-03-13 15:21 UTC, ievetrovdev commented on lesson_7/Task_3.kt
> +    val number = readln().toUInt()
А зачем сначала переводить в unit а потом в int

2024-03-13 16:45 UTC, Sguruu commented on lesson_7/Task_3.kt
> +    val number = readln().toUInt()
Хотел быть уверенном, в том что там точно не отрицательное число будет, но задумка не удалась, так как for работает только с int :(

Поправлю

2024-03-14 06:42 UTC, ievetrovdev commented on lesson_7/Task_3.kt
> +    val number = readln().toUInt()
В таком случае лучше использовать if
, иначе просто ошибку словишь

2024-03-14 06:42 UTC, ievetrovdev approved these changes

2024-03-26 16:38 UTC, merged