Урок 9 Задача 3
Sguruu/kurs_kotlin_basic pull request #9
Opened 2024-04-17 19:57 UTC by Sguruu

2024-04-18 07:11 UTC, ievetrovdev requested changes

2024-04-18 07:11 UTC, ievetrovdev commented on lesson_9/Task_3.kt
> +    val infoEggs = listIngredients[0]
Не лучшее решение, если размер списка увеличится, то придется переписывать код. Попробуй использовать map для преобразования списка

2024-04-18 19:56 UTC, Sguruu commented on lesson_9/Task_3.kt
> +    val infoEggs = listIngredients[0]
Поправил

2024-04-19 07:37 UTC, ievetrovdev approved these changes

2024-05-02 12:11 UTC, merged